# Generated by Django 4.1.1 on 2022-09-27 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Image',
        ),
    ]
